### GET ALL
GET http://localhost:8889/api/v1/activitylogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAwYTE3NTZhY2M0YmZiZjFmYzc3NTkiLCJlbWFpbCI6ImRhdG5ndXllbmhvdGhlQGdtYWlsLmNvbSIsImlhdCI6MTc0NDg4MzE3MywiZXhwIjoxNzQ0OTY5NTczfQ.EQpzcr8YZvNmWxql4OkE4ofN66k44Xa9_EKjJdeMjHw

### get by id
GET http://localhost:8889/api/v1/activitylogs/68008f853e5908d972fabcc7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAwYTE3NTZhY2M0YmZiZjFmYzc3NTkiLCJlbWFpbCI6ImRhdG5ndXllbmhvdGhlQGdtYWlsLmNvbSIsImlhdCI6MTc0NDg4MzE3MywiZXhwIjoxNzQ0OTY5NTczfQ.EQpzcr8YZvNmWxql4OkE4ofN66k44Xa9_EKjJdeMjHw

### create

POST http://localhost:8889/api/v1/activitylogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAwYTE3NTZhY2M0YmZiZjFmYzc3NTkiLCJlbWFpbCI6ImRhdG5ndXllbmhvdGhlQGdtYWlsLmNvbSIsImlhdCI6MTc0NDg4MzE3MywiZXhwIjoxNzQ0OTY5NTczfQ.EQpzcr8YZvNmWxql4OkE4ofN66k44Xa9_EKjJdeMjHw

{
    "action": "update",
    "entityType": "Category",
    "entityId": "67f49e1fa6510d661ec654c7",
    "description": "update name category",
    "metadata": { 
        "previousStatus": "processing", 
        "newStatus": "shipped" 
    },
    "ipAddress": "203.0.113.15",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    "user": "67f4cab25268f5fb727f9bea"
}

### update by id
PUT http://localhost:8889/api/v1/activitylogs/67d9452369975e3a9c1c24cc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UyNWMzM2EzMTcyMWM3ZGFiOTQyNzciLCJlbWFpbCI6ImRhdG5ndXllbmhvdGhlQGdtYWlsLmNvbSIsImlhdCI6MTc0MzA0MTU3NywiZXhwIjoxNzQzMTI3OTc3fQ.SohKOzQiMD4wgKf1_QPSKwwnbkIlKb7IfYDWuhxWOCQ

{
    "thumbnail": "http://localhost:8889/uploads/activitylogs/scanner.png"
}

### delete by id
DELETE http://localhost:8889/api/v1/activitylogs/680090fdc2a0d94c2f3383c7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAwYTE3NTZhY2M0YmZiZjFmYzc3NTkiLCJlbWFpbCI6ImRhdG5ndXllbmhvdGhlQGdtYWlsLmNvbSIsImlhdCI6MTc0NDg4MzE3MywiZXhwIjoxNzQ0OTY5NTczfQ.EQpzcr8YZvNmWxql4OkE4ofN66k44Xa9_EKjJdeMjHw