### GET ALL
GET http://localhost:8889/api/v1/products?price_gte=15000000&price_lte=20000000

### get by id
GET http://localhost:8889/api/v1/products/680615c848f0a1f1f4eb4d6d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAwYTE3NTZhY2M0YmZiZjFmYzc3NTkiLCJlbWFpbCI6ImRhdG5ndXllbmhvdGhlQGdtYWlsLmNvbSIsImlhdCI6MTc0NTIyOTIyNywiZXhwIjoxNzQ1MzE1NjI3fQ.84w1mGGkXLRufKdd-yqxF1aUMj2MVhKnryvA19O7C4A

### create pc, laptop

POST http://localhost:8889/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODI0MDQwMjA5MzQwOGRhMzNjNzM4ZjMiLCJlbWFpbCI6InRoZWRhdEBnbWFpbC5jb20iLCJpYXQiOjE3NTAxMzA5MjgsImV4cCI6MTc1MDIxNzMyOH0.WCjIkwXS_INyQRTORn1ronnlfYkymBEBlKPdqw2SFrk

{
  "product_name": "Laptop ASUS Vivobook S 16 OLED M5606KA RI016WS",
  "description": "Laptop 16″ hiển thị đẹp (OLED 3K, sáng, màu chính xác), cấu hình khỏe phục vụ học tập, thiết kế cơ bản, code nhẹ, máy mỏng nhẹ, nhiều cổng kết nối, dùng cả ngày không cần sạc.",
  "price": 30990000,
  "salePrice": 29990000,
  "stock": 100,
  "images": [
  "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_13_77e05487fd234fec89d381ce4949dab6_grande.webp",
  "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_06_1ad6d96fef1846c7886be3764be336c8_grande.webp",
  "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_07_2f4099454b554ff0b782d2ebe54316d6_grande.webp",
  "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_08_5e06dfcecc364be0824c931c602e3937_grande.webp",
  "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_12_deef605ba52c4d7497d40b1755a0fcd2_grande.webp",
  "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_web_04_d99301dde35b436088e8b3428f39fe81_grande.webp",
  "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/us_vivobook_s16_m5606ka_product_photo_8k_neutral_black_05_camera_close_ecca76dc9dcb4888996bc9cc18b399e8_grande.webp"
],
  "attributes": [
  { "name": "CPU", "value": "AMD Ryzen™ AI 7 350 2.0GHz (24MB Cache, up to 5.0GHz, 8 cores, 16 Threads)", "time": "36 Tháng" },
  { "name": "RAM", "value": "24GB LPDDR5X on board", "time": "36 Tháng" },
  { "name": "Ổ cứng", "value": "512GB M.2 NVMe™ PCIe® 4.0 SSD", "time": "36 Tháng" },
  { "name": "VGA - Card đồ họa", "value": "AMD Radeon™ Graphics", "time": "36 Tháng" },
  { "name": "Màn hình", "value": "16\" 3K (2880 x 1800) OLED, 120Hz, HDR, 100% DCI-P3, VESA Display HDR True Black 500", "time": "36 Tháng" },
  { "name": "Cổng giao tiếp", "value": "1x USB 4.0 Gen 3 Type-C, 1x USB 3.2 Gen 1 Type-C, 2x USB 3.2 Gen 1 Type-A, 1x HDMI 2.1, 1x 3.5mm Audio Jack, Micro SD card reader", "time": "36 Tháng" },
  { "name": "Bàn phím", "value": "Backlit Chiclet Keyboard 1-Zone RGB without Num-key With Copilot key", "time": "36 Tháng" },
  { "name": "Audio", "value": "Smart Amp Technology, harman/kardon, Built-in speaker, Built-in array microphone", "time": "36 Tháng" },
  { "name": "Webcam", "value": "FHD camera with IR and privacy shutter, Windows Hello supported", "time": "36 Tháng" },
  { "name": "Hệ điều hành", "value": "Windows 11 Home + Microsoft Office Home 2024 + Microsoft 365 Basic", "time": "36 Tháng" },
  { "name": "Pin", "value": "75WHrs, 4S1P, 4-cell Li-ion", "time": "36 Tháng" },
  { "name": "Trọng lượng", "value": "1.5 kg", "time": "36 Tháng" },
  { "name": "Màu sắc", "value": "Neutral Black", "time": "36 Tháng" },
  { "name": "Kích thước", "value": "35.36 x 24.69 x 1.39 ~ 1.59 cm", "time": "36 Tháng" }
],
  "rating": 4.7,
  "tags": [
  "R7 AI 350",
  "AMD Radeon™ Graphics",
  "24 GB",
  "512 GB",
  "16 inch 3K OLED"
],
  "bestSale": false,
  "flashSale": false,
  "promotion": [
    "Trả góp 0%"
  ],
  "contentBlock": [
    {
      "type": "text",
      "content": "<strong>Đánh giá chi tiết laptop ASUS Vivobook S 16 OLED M5606KA RI016WS</strong>"
    },
    {
      "type": "text",
      "content": "ASUS Vivobook S 16 OLED M5606KA RI016WS là sự kết hợp tuyệt vời giữa thiết kế mỏng nhẹ và công nghệ hiện đại. Chip AMD Ryzen™ AI 7 350 Processor cung cấp nguồn sức mạnh đặc biệt ấn tượng, đồng thời hỗ trợ các công nghệ AI rất hiệu quả. Ngoại hình máy cực kì đơn giản, nhưng toát lên vẻ đẹp sang trọng, cao cấp thu hút người dùng ngay từ cái nhìn đầu tiên. Hãy cùng GEARVN tìm hiểu thông số kĩ thuật của chiếc laptop ASUS này nhé!"
    },
    {
      "type": "image",
      "src": "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_06_1ad6d96fef1846c7886be3764be336c8_grande.webp",
      "alt": "image_1"
    },
     {
      "type": "text",
      "content": "<strong>Thiết kế tinh tế và tính di động cao</strong>"
    },
    {
      "type": "text",
      "content": "ASUS Vivobook S 16 OLED M5606KA RI016WS gây ấn tượng ngay từ cái nhìn đầu tiên với thiết kế mỏng nhẹ, hiện đại và thanh lịch. Vỏ máy được chế tác từ chất liệu cao cấp, mang lại cảm giác chắc chắn và bền bỉ khi cầm nắm. Các đường nét được gia công tỉ mỉ, tạo nên vẻ ngoài sang trọng và chuyên nghiệp. Vivobook S 16 OLED M5606KA RI016WS có khung máy siêu mỏng với trọng lượng tổng thể chỉ 1,5kg. Đây là mẫu laptop mỏng nhẹ lý tưởng cho những ai có nhu cầu mang theo laptop để làm việc hoặc học tập thường xuyên. Dù sở hữu màn hình lớn 16 inch nhưng nhờ thiết kế viền bao quanh cực mỏng, sản phẩm vẫn đạt kích cỡ tổng thể cực gọn gàng, thuận tiện để sắp xếp và cất gọn trong balo, túi xách."
    },
    {
      "type": "image",
      "src": "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_08_5e06dfcecc364be0824c931c602e3937_grande.webp",
      "alt": "image_2"
    },
    {
      "type": "text",
      "content": "<strong>Hiệu năng mạnh mẽ cho mọi tác vụ bạn cần</strong>"
    },
    {
      "type": "text",
      "content": "ASUS Vivobook S 16 OLED M5606KA RI016WS được trang bị bộ vi xử lý AMD Ryzen™ AI 7 350 với 8 nhân và 16 luồng. Đây không chỉ là một trong những con CPU AMD Ryzen AI mạnh mẽ nhất dành cho laptop hiện nay mà còn đáp ứng hoàn hảo cho những nhu cầu liên quan đến AI, từ hiệu năng đến thời lượng sử dụng bền bỉ. Ngoài ra, đây cũng là một lợi thế giúp thiết bị đáp ứng mượt mà các tác vụ như chơi game, lập trình, đồ họa và chỉnh sửa video."
    },
    {
      "type": "image",
      "src": "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_06_1ad6d96fef1846c7886be3764be336c8_grande.webp",
      "alt": "image_3"
    },
    {
      "type": "text",
      "content": "<strong>Đắm chìm vào màn hình 16 inch OLED tuyệt sắc</strong>"
    },
    {
      "type": "text",
      "content": "Điểm nhấn đặc biệt của ASUS Vivobook S 16 OLED M5606KA RI016WS chính là màn hình OLED kích thước 16 inch. Công nghệ OLED mang đến những ưu điểm vượt trội về chất lượng hiển thị, bao gồm độ tương phản cực cao, màu đen sâu thẳm và dải màu rộng giúp biến chiếc laptop OLED này là một lựa chọn đáng cân nhắc cho các game thủ, những người làm đồ họa hoặc những ai đam mê các nội dung giải trí. Ngoài ra, tần số quét 120Hz khiến cho việc đắm chìm vào thế giới game và phim ảnh trở nên sống động tuyệt đối. Không chỉ vậy, màn hình này còn hỗ trợ 100% DCI-P3, đảm bảo màu sắc trên màn hình sẽ được hiển thị chính xác, sống động và trung thực. Độ tương phản 1.000.000:1 của sản phẩm khiến cho các nội dung HDR được diễn đạt với chiều sâu ấn tượng hơn bao giờ hết."
    },
    {
      "type": "image",
      "src": "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_07_2f4099454b554ff0b782d2ebe54316d6_grande.webp",
      "alt": "image_4"
    },
    {
      "type": "text",
      "content": "<strong>Đa dạng kết nối</strong>"
    },
    {
      "type": "text",
      "content": "ASUS Vivobook S 16 OLED M5606KA RI016WS được trang bị đầy đủ các cổng kết nối tiêu chuẩn nhất giúp bạn dễ dàng kết nối với các thiết bị ngoại vi khác (loa, chuột,...)"
    },
    {
      "type": "image",
      "src": "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/us_vivobook_s16_m5606ka_product_photo_8k_neutral_black_05_camera_close_ecca76dc9dcb4888996bc9cc18b399e8_grande.webp",
      "alt": "image_5"
    },
    {
      "type": "text",
      "content": "Ngoài những điểm mạnh về thiết kế, màn hình và hiệu năng, ASUS Vivobook S 16 OLED M5606KA RI016WS còn được trang bị nhiều tính năng hữu ích khác, nâng cao trải nghiệm người dùng"
    },
    {
      "type": "image",
      "src": "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_12_deef605ba52c4d7497d40b1755a0fcd2_grande.webp",
      "alt": "image_6"
    },
     {
      "type": "text",
      "content": "Bài viết trên đây đã điểm qua một vài thông số đáng chú ý của chiếc laptop ASUS Vivobook S 16 OLED M5606KA RI016WS. Có thể thấy ASUS Vivobook S 16 OLED M5606KA RI016WS là một sự lựa chọn tuyệt vời cho những ai đang tìm kiếm một chiếc laptop có màn hình OLED sắc nét, hiệu năng ổn định và thiết kế đẹp mắt."
    },
     {
      "type": "text",
      "content": "Đừng quên để lại bình luận bên dưới nếu có bất kì thắc mắc nào về sản phẩm hoặc liên hệ trực tiếp cho chúng tôi qua số hotline 19005301 để được tư vấn và giải đáp ngay nhé!"
    }
  ],
  "category": "680516243556be73141264bc",
  "brand": "6805e67efea56b05826cc2d6",
  "vendor": "6805ebf6c350793d7da27a88"
}


### create MOUSE

POST http://localhost:8889/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAwYTE3NTZhY2M0YmZiZjFmYzc3NTkiLCJlbWFpbCI6ImRhdG5ndXllbmhvdGhlQGdtYWlsLmNvbSIsImlhdCI6MTc0NTIyOTIyNywiZXhwIjoxNzQ1MzE1NjI3fQ.84w1mGGkXLRufKdd-yqxF1aUMj2MVhKnryvA19O7C4A

{
  "product_name": "Chuột Steelseries Aerox 3 Wireless Snow Edition",
  "price": 3490000,
  "salePrice": 2490000,
  "stock": 100,
  "images": [
    "http://localhost:8889/uploads/Chuot_Steelseries_Aerox_3_Wireless_Snow_Edition/eries_aerox_3_wireless_snow_edition_1_5508676fc8d74c96aab9a00d2d0b2e54_12cd3276efd34e62b8bc64c833ac34f2_grande.webp",
    "http://localhost:8889/uploads/Chuot_Steelseries_Aerox_3_Wireless_Snow_Edition/eries_aerox_3_wireless_snow_edition_2_931fccf8e98141128c0513c6aa66a1c8_4b5b1d12e8ca462e8409ae471edbe88e_gran.webp",
    "http://localhost:8889/uploads/Chuot_Steelseries_Aerox_3_Wireless_Snow_Edition/eries_aerox_3_wireless_snow_edition_3_c08f23fd7f654c53b0307eb8fc667796_0c51985f6169408dbc9fe5ba75d2e9f7_gran.webp",
    "http://localhost:8889/uploads/Chuot_Steelseries_Aerox_3_Wireless_Snow_Edition/eries_aerox_3_wireless_snow_edition_4_93ff52a35fe94fa9b1a5499b7de3ffef_5a9e671f50064922ac95c8d24d7758fb_gran.webp"
  ],
  "rating": 4.2,
  "tags": [
  "Pin rời",
  "Không dây",
  "DPI - 1.000"
],
  "bestSale": false,
  "flashSale": false,
  "category": "6805190b3556be73141264ec",
  "brand": "6805e680fea56b05826cc31d",
  "vendor": "6805ebf6c350793d7da27a88"
}

### create KEYBOARD

POST http://localhost:8889/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFjYWIzZmY2MTk4MjRmMWFhYzQzYzkiLCJlbWFpbCI6Im5ndXllbmhvdGhlZGF0MjAyNUBnbWFpbC5jb20iLCJpYXQiOjE3NDY5NzY5MjAsImV4cCI6MTc0NzA2MzMyMH0.ADGIMnvcovAe4lyHCJOaxwunxF9cLUcGjQPyb8V3SeM

{
  "product_name": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch",
  "price": 4990000,
  "salePrice": 3690000,
  "stock": 100,
  "images": [
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_1_f163cb90590f4640bb0.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_1_42b4ca48ebbf461.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_2_f5e4262062d44022b0d.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_3_b1d37aab419940ed90a.webp"
  ],
  "rating": 4.9,
  "tags": [
  "Không dây",
  "ABS",
  "RGB"
],
  "bestSale": false,
  "flashSale": false,
    "contentBlock": [
    {
      "type": "text",
      "content": "<strong>Đánh giá chi tiết bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch</strong>"
    },
    {
      "type": "text",
      "content": "Dù bạn có am hiểu về công nghệ hay không thì bạn chắc chắn vẫn biết đến các thiết bị công nghệ của thương hiệu Asus như laptop Asus, màn hình Asus… Bên cạnh đó thì các thiết bị Gaming Gear đặc biệt là không thể nhắc đến Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch với nhiều công năng vượt trội, hãy cùng GEARVN tìm hiểu ngay sau đây."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/n_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___1__1024x1024.jpg",
      "alt": "image_1"
    },
    {
      "type": "text",
      "content": "<strong>Thiết kế thu gọn tối đa với bàn phím 96%</strong>"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless được xem là bàn phím 96% khi vẫn giữ lại toàn bộ các phím nhưng lại được thu gọn khoảng cách một cách tối đa, từ đó mà kích thước của chiếc bàn phím này chỉ lớn hơn bàn phím tiêu chuẩn 80% chỉ 1cm. Tuy là được thu gọn thiết kế một cách tối đa nhưng bàn phím lại mang trong mình vẻ cứng cáp và hoành tráng khi có cho mình trọng lượng"
    },
     {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___11__1024x1024.webp",
      "alt": "image_2"
    },
    {
      "type": "text",
      "content": "<strong>Màu sắc LED đồng bộ với nhiều thiết bị</strong>"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless sở hữu cho mình bộ LED RGB trong từng phím. Cùng với đó nếu bạn sở hữu laptop Asus, chuột Asus, tai nghe Asus các gamer sẽ còn được có thể sử dụng thêm tính năng Asus Aura sync đồng bộ ánh sáng và màu sắc cho mọi thiết bị Asus. Việc sở hữu khả năng thay đổi và kết hợp màu sắc cho sản phẩm công nghệ giúp cho trải nghiệm thư giãn cũng như chơi game của các gamer được nâng cấp lên một level mới."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___12__1024x1024.webp",
      "alt": "image_3"
    },
    {
      "type": "text",
      "content": "<strong>Sự kết hợp hoàn hảo cho dân gaming</strong>"
    },
    {
      "type": "text",
      "content": "Bạn sẽ có thể trải nghiệm cảm giác chơi game thuận tiện nhất khi bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch sở hữu cho mình tính năng Anti -Ghosting giúp anh em linh hoạt các nút bấm nhằm né được những đòn đánh và phản công địch một cách tối ưu. Bên cạnh đó, anh em có thể kích hoạt thêm Marco Key vào bất kỳ phím nào trên bàn phím để có thể linh hoạt và tiết kiệm thời gian nhất trong quá trình sử dụng."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/n_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___8__1024x1024.webp",
      "alt": "image_4"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch có thể là sự lựa chọn tối ưu của các anh em gamer không chỉ vì các tính năng kể trên mà chiếc bàn phím này còn hỗ trợ kết nối đa thiết bị thuận lợi cho việc sử dụng của anh em trên mọi mặt trận."
    }
  ],
  "category": "680518eb3556be73141264e8",
  "brand": "6805e67efea56b05826cc2d6",
  "vendor": "6805ebf6c350793d7da27a88"
}

### test create with not salePrince

POST http://localhost:8889/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODI0MDQwMjA5MzQwOGRhMzNjNzM4ZjMiLCJlbWFpbCI6InRoZWRhdEBnbWFpbC5jb20iLCJpYXQiOjE3NDg4MzI1MjUsImV4cCI6MTc0ODkxODkyNX0.tdeOc8lj8GyQbjIyi8hc6TXdzX5EwJLne5Pw_YXlXUI

{
  "product_name": "test with not salePrince",
  "price": 4990000,
  "stock": 100,
  "images": [
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_1_f163cb90590f4640bb0.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_1_42b4ca48ebbf461.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_2_f5e4262062d44022b0d.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_3_b1d37aab419940ed90a.webp"
  ],
  "rating": 4.9,
  "tags": [
  "Không dây",
  "ABS",
  "RGB"
],
  "bestSale": false,
  "flashSale": false,
    "contentBlock": [
    {
      "type": "text",
      "content": "<strong>Đánh giá chi tiết bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch</strong>"
    },
    {
      "type": "text",
      "content": "Dù bạn có am hiểu về công nghệ hay không thì bạn chắc chắn vẫn biết đến các thiết bị công nghệ của thương hiệu Asus như laptop Asus, màn hình Asus… Bên cạnh đó thì các thiết bị Gaming Gear đặc biệt là không thể nhắc đến Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch với nhiều công năng vượt trội, hãy cùng GEARVN tìm hiểu ngay sau đây."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/n_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___1__1024x1024.jpg",
      "alt": "image_1"
    },
    {
      "type": "text",
      "content": "<strong>Thiết kế thu gọn tối đa với bàn phím 96%</strong>"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless được xem là bàn phím 96% khi vẫn giữ lại toàn bộ các phím nhưng lại được thu gọn khoảng cách một cách tối đa, từ đó mà kích thước của chiếc bàn phím này chỉ lớn hơn bàn phím tiêu chuẩn 80% chỉ 1cm. Tuy là được thu gọn thiết kế một cách tối đa nhưng bàn phím lại mang trong mình vẻ cứng cáp và hoành tráng khi có cho mình trọng lượng"
    },
     {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___11__1024x1024.webp",
      "alt": "image_2"
    },
    {
      "type": "text",
      "content": "<strong>Màu sắc LED đồng bộ với nhiều thiết bị</strong>"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless sở hữu cho mình bộ LED RGB trong từng phím. Cùng với đó nếu bạn sở hữu laptop Asus, chuột Asus, tai nghe Asus các gamer sẽ còn được có thể sử dụng thêm tính năng Asus Aura sync đồng bộ ánh sáng và màu sắc cho mọi thiết bị Asus. Việc sở hữu khả năng thay đổi và kết hợp màu sắc cho sản phẩm công nghệ giúp cho trải nghiệm thư giãn cũng như chơi game của các gamer được nâng cấp lên một level mới."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___12__1024x1024.webp",
      "alt": "image_3"
    },
    {
      "type": "text",
      "content": "<strong>Sự kết hợp hoàn hảo cho dân gaming</strong>"
    },
    {
      "type": "text",
      "content": "Bạn sẽ có thể trải nghiệm cảm giác chơi game thuận tiện nhất khi bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch sở hữu cho mình tính năng Anti -Ghosting giúp anh em linh hoạt các nút bấm nhằm né được những đòn đánh và phản công địch một cách tối ưu. Bên cạnh đó, anh em có thể kích hoạt thêm Marco Key vào bất kỳ phím nào trên bàn phím để có thể linh hoạt và tiết kiệm thời gian nhất trong quá trình sử dụng."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/n_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___8__1024x1024.webp",
      "alt": "image_4"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch có thể là sự lựa chọn tối ưu của các anh em gamer không chỉ vì các tính năng kể trên mà chiếc bàn phím này còn hỗ trợ kết nối đa thiết bị thuận lợi cho việc sử dụng của anh em trên mọi mặt trận."
    },
    {
      "type": "image",
      "src": "http://ecommerce-technology-store.onrender.com/uploads/Laptop_ASUS_Vivobook_S_16_OLED_M5606KA_RI016WS/asus_vivobook_s16_m5606ka_product_photo_8k_neutral_black_12_deef605ba52c4d7497d40b1755a0fcd2_grande.webp",
      "alt": "image_4"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch có thể là sự lựa chọn tối ưu của các anh em gamer không chỉ vì các tính năng kể trên mà chiếc bàn phím này còn hỗ trợ kết nối đa thiết bị thuận lợi cho việc sử dụng của anh em trên mọi mặt trận."
    }
  ],
  "category": "680518eb3556be73141264e8",
  "brand": "6805e67efea56b05826cc2d6",
  "vendor": "6805ebf6c350793d7da27a88"
}


### update by id
PUT http://localhost:8889/api/v1/products/6820e53880a8734921371e03
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFjYWIzZmY2MTk4MjRmMWFhYzQzYzkiLCJlbWFpbCI6Im5ndXllbmhvdGhlZGF0MjAyNUBnbWFpbC5jb20iLCJpYXQiOjE3NDY5NzY5MjAsImV4cCI6MTc0NzA2MzMyMH0.ADGIMnvcovAe4lyHCJOaxwunxF9cLUcGjQPyb8V3SeM

{
    "product_name": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch",
    "description": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch là một lựa chọn cao cấp dành cho game thủ và người dùng chuyên nghiệp, kết hợp giữa thiết kế nhỏ gọn, hiệu suất cao và khả năng tùy biến linh hoạt."
}

### delete by id
DELETE http://localhost:8889/api/v1/products/67deea930d9bae179e3bc9df