### GET ALL
GET http://localhost:8889/api/v1/products?price_gte=15000000&price_lte=20000000

### get by id
GET http://localhost:8889/api/v1/products/680615c848f0a1f1f4eb4d6d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAwYTE3NTZhY2M0YmZiZjFmYzc3NTkiLCJlbWFpbCI6ImRhdG5ndXllbmhvdGhlQGdtYWlsLmNvbSIsImlhdCI6MTc0NTIyOTIyNywiZXhwIjoxNzQ1MzE1NjI3fQ.84w1mGGkXLRufKdd-yqxF1aUMj2MVhKnryvA19O7C4A

### create pc, laptop

POST http://localhost:8889/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBkZjk1OTgxZmU4ZGI4MmExY2Y5ZDMiLCJlbWFpbCI6Im5ndXllbmhvdGhlZGF0ODhAZ21haWwuY29tIiwiaWF0IjoxNzQ2NjMzNDgxLCJleHAiOjE3NDY3MTk4ODF9.49HUoS_0MwJYrXQApaWqv3riAQmwLRNNqbAz0ZnPNMg

{
  "product_name": "PC GVN Intel i3-12100F/ VGA RX 6500XT",
  "description": "PC GVN Intel i3-12100F/ VGA RX 6500XT mang lại trải nghiệm hình ảnh tốt hơn với trang bị màn hình OLED. Thiết kế mỏng nhẹ cùng cấu hình mạnh mẽ cho phép người dùng nâng cao hiệu suất khi làm việc.",
  "price": 11430000,
  "salePrice": 10490000,
  "stock": 100,
  "images": [
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/pc_gvn_rx6600___3_762ba90a94904a50809a93355cd819a7_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/pba_poster_viet_e85938a153454a50bfbe1df4b4200b9d_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/pc_gvn_rx6600___4_b0f0beb2642a42399c305f3638d2c364_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/pc_gvn_rx6600___1_c0c7d32f4c274ff280c9e75a3b8b0213_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/pc_gvn_rx6600___2_9577b2a53e584c10b3f50521079dd5cf_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/pc_gvn_rx6600___5_b2d8837656c5443fac89ab0c84f93ba0_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_01_eb1af161f55b46d3b518cd51b1b88b75_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_02_a63b507db4cd42558caa4ff0e14d668f_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_03_5f342d16dc6e4438b9018fd0c0d2df1a_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_04_a989ab65d1464f5f8567d07c21321acd_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_05_35e780ef246c4f3fb0ca74f2d9b348af_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_09_beeb3df03d90441daaecf3466b2a72ea_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_10_d59fe170a38743009de0a47b84e0376c_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_11_8d17d4e5bd634820b7906a759229790f_grande.webp",
    "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_12_fa1c19e0b3f344308036ce6a45f9f555_grande.webp"
  ],
  "attributes": [
  { "name": "Mainboard", "value": "Mainboard ASUS PRIME H610M-A WIFI D4", "time": "36 Tháng" },
  { "name": "CPU", "value": "Intel Core i3 12100F / 3.3GHz Turbo 4.3GHz / 4 Nhân 8 Luồng / 12MB / LGA 1700", "time": "36 Tháng" },
  { "name": "RAM", "value": "Ram V-Color Skywalker Plus 1x8 3600 RGB Black DDR4", "time": "36 Tháng" },
  { "name": "VGA - Card đồ họa", "value": "ASUS Dual Radeon RX 6500 XT V2 OC Edition 4GB GDDR6", "time": "36 Tháng" },
  { "name": "HDD", "value": "Có thể tùy chọn Nâng cấp", "time": "24 Tháng" },
  { "name": "SSD", "value": "PNY CS900 250GB Sata3", "time": "36 Tháng" },
  { "name": "PSU", "value": "Deepcool PF450D - 80 Plus (450W)", "time": "36 Tháng" },
  { "name": "Case", "value": "Xigmatek QUANTUM 3GF", "time": "12 Tháng" }
],
  "rating": 4.9,
  "tags": [
  "i3-12100F",
  "RX 6500XT",
  "H610",
  "8GB",
  "250GB"
],
  "bestSale": true,
  "flashSale": false,
  "promotion": [
    "Tặng ngay 1 x Ram V-Color Skywalker Plus 1x8GB 3600 RGB Black DDR4 trị giá 550.000₫.",
    "Tặng ngay 1 x Quạt XIGMATEK INFINITY BLACK 120mm (EN44564) - RGB FIXED trị giá 90.000₫."
  ],
  "contentBlock": [
    {
      "type": "text",
      "content": "<strong>Chi tiết về PC GVN Intel i3-12100F/ VGA RX 6500XT</strong>"
    },
    {
      "type": "text",
      "content": "Được trang bị vi xử lý Intel Core i3 -12100F, chiếc PC i3 này đảm bảo hiệu năng xử lý ổn định cho các tác vụ hàng ngày. Với kiến trúc 4 nhân 8 luồng, con chip này dễ dàng xử lý đa nhiệm, cho phép bạn làm việc, lướt web và giải trí cùng lúc mà không gặp phải tình trạng giật lag. Công nghệ sản xuất tiên tiến giúp tối ưu hóa hiệu suất năng lượng, giảm thiểu tiêu thụ điện năng."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_01_eb1af161f55b46d3b518cd51b1b88b75_grande.webp",
      "alt": "image_1"
    },
     {
      "type": "text",
      "content": "<strong>Đồ họa sắc nét với GPU AMD Radeon RX 6500XT</strong>"
    },
    {
      "type": "text",
      "content": "Card đồ họa AMD Radeon RX 6500XT là một lựa chọn hợp lý cho những ai muốn trải nghiệm đồ họa mượt mà ở mức cài đặt trung bình. Với kiến trúc RDNA 2 tiên tiến, card đồ họa này mang đến hiệu suất chơi game ấn tượng, đặc biệt là với các tựa game eSports phổ biến. Bộ nhớ GDDR6 dung lượng lớn đảm bảo việc xử lý hình ảnh diễn ra nhanh chóng và mượt mà."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_02_a63b507db4cd42558caa4ff0e14d668f_grande.webp",
      "alt": "image_2"
    },
    {
      "type": "text",
      "content": "<strong>Bộ nhớ RAM của PC GVN Intel i3-12100F đáp ứng nhu cầu đa nhiệm</strong>"
    },
    {
      "type": "text",
      "content": "Được trang bị 8GB RAM DDR4, chiếc PC này đủ sức để bạn mở nhiều tab trình duyệt, ứng dụng cùng lúc mà không gặp phải tình trạng giật lag. Bạn có thể thoải mái làm việc với các phần mềm văn phòng, chỉnh sửa ảnh cơ bản hoặc thậm chí là stream một số tựa game nhẹ."
    },
    {
      "type": "text",
      "content": "<strong>Ổ cứng SSD NVMe - Tốc độ và không gian lưu trữ</strong>"
    },
    {
      "type": "text",
      "content": "Việc trang bị ổ cứng SSD NVMe giúp cho chiếc PC khởi động nhanh chóng, load ứng dụng và game mượt mà hơn so với ổ cứng HDD truyền thống. Dung lượng ổ cứng SSD thường khá lớn, đủ để bạn lưu trữ hệ điều hành, game, ứng dụng và các tập tin cá nhân."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_04_a989ab65d1464f5f8567d07c21321acd_grande.webp",
      "alt": "image_3"
    },
    {
      "type": "text",
      "content": "<strong>Mainboard ASUS PRIME H610M-CS D4</strong>"
    },
    {
      "type": "text",
      "content": "Bảng mạch chủ ASUS PRIME H610M-CS D4 là một lựa chọn đáng tin cậy, cung cấp nền tảng vững chắc cho hệ thống. Với thiết kế tối ưu, bảng mạch chủ này đảm bảo sự ổn định và tương thích tốt với các linh kiện khác."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_05_35e780ef246c4f3fb0ca74f2d9b348af_grande.webp",
      "alt": "image_4"
    },
    {
      "type": "text",
      "content": "<strong>Nguồn cung cấp năng lượng ổn định</strong>"
    },
    {
      "type": "text",
      "content": "Nguồn cung cấp năng lượng đóng vai trò quan trọng trong việc đảm bảo hoạt động ổn định của hệ thống. Chiếc PC này được trang bị nguồn đủ công suất để cung cấp năng lượng cho tất cả các linh kiện, giúp hệ thống hoạt động bền bỉ trong thời gian dài."
    },
    {
      "type": "text",
      "content": "<strong>Nâng cấp RAM và SSD dễ dàng</strong>"
    },
    {
      "type": "text",
      "content": "Việc nâng cấp RAM và ổ cứng SSD cho chiếc PC này khá đơn giản và mang lại hiệu quả rõ rệt. Hầu hết các mainboard đi kèm với CPU Intel i3-12100F đều hỗ trợ RAM DDR4 với tốc độ cao. Bạn có thể dễ dàng thay thế thanh RAM hiện tại hoặc thêm vào một thanh RAM mới để tăng tổng dung lượng."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_09_beeb3df03d90441daaecf3466b2a72ea_grande.webp",
      "alt": "image_5"
    },
    {
      "type": "text",
      "content": "Ngoài ra, bạn cũng có thể sử dụng thêm một khe SATA để lắp đặt ổ cứng SSD SATA (nếu mainboard hỗ trợ). Việc nâng cấp ổ cứng SSD sẽ giúp máy tính của bạn hoạt động nhanh chóng và mượt mà hơn, đặc biệt là khi khởi động hệ điều hành, mở ứng dụng và chơi game."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/PC_GVN_Intel_i3_12100F_VGA_RX_6500XT/post_12_fa1c19e0b3f344308036ce6a45f9f555_grande.webp",
      "alt": "image_6"
    },
    {
      "type": "text",
      "content": "Nếu bạn đang tìm kiếm một bộ PC Gaming vừa túi tiền mà vẫn đảm bảo hiệu năng cao để chiến game, PC GVN Intel i3-12100F/ VGA RX 6500XT là một sự lựa chọn đáng cân nhắc với mức giá trung bình trên. Ghé ngay showroom GEARVN để trực tiếp trải nghiệm sản phẩm một cách tốt nhất nhé!"
    }
  ],
  "category": "6805167c3556be73141264c0",
  "brand": "6805e67efea56b05826cc2d6",
  "vendor": "6805ebf6c350793d7da27a88"
}


### create MOUSE

POST http://localhost:8889/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAwYTE3NTZhY2M0YmZiZjFmYzc3NTkiLCJlbWFpbCI6ImRhdG5ndXllbmhvdGhlQGdtYWlsLmNvbSIsImlhdCI6MTc0NTIyOTIyNywiZXhwIjoxNzQ1MzE1NjI3fQ.84w1mGGkXLRufKdd-yqxF1aUMj2MVhKnryvA19O7C4A

{
  "product_name": "Chuột Steelseries Aerox 3 Wireless Snow Edition",
  "price": 3490000,
  "salePrice": 2490000,
  "stock": 100,
  "images": [
    "http://localhost:8889/uploads/Chuot_Steelseries_Aerox_3_Wireless_Snow_Edition/eries_aerox_3_wireless_snow_edition_1_5508676fc8d74c96aab9a00d2d0b2e54_12cd3276efd34e62b8bc64c833ac34f2_grande.webp",
    "http://localhost:8889/uploads/Chuot_Steelseries_Aerox_3_Wireless_Snow_Edition/eries_aerox_3_wireless_snow_edition_2_931fccf8e98141128c0513c6aa66a1c8_4b5b1d12e8ca462e8409ae471edbe88e_gran.webp",
    "http://localhost:8889/uploads/Chuot_Steelseries_Aerox_3_Wireless_Snow_Edition/eries_aerox_3_wireless_snow_edition_3_c08f23fd7f654c53b0307eb8fc667796_0c51985f6169408dbc9fe5ba75d2e9f7_gran.webp",
    "http://localhost:8889/uploads/Chuot_Steelseries_Aerox_3_Wireless_Snow_Edition/eries_aerox_3_wireless_snow_edition_4_93ff52a35fe94fa9b1a5499b7de3ffef_5a9e671f50064922ac95c8d24d7758fb_gran.webp"
  ],
  "rating": 4.2,
  "tags": [
  "Pin rời",
  "Không dây",
  "DPI - 1.000"
],
  "bestSale": false,
  "flashSale": false,
  "category": "6805190b3556be73141264ec",
  "brand": "6805e680fea56b05826cc31d",
  "vendor": "6805ebf6c350793d7da27a88"
}

### create KEYBOARD

POST http://localhost:8889/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFjYWIzZmY2MTk4MjRmMWFhYzQzYzkiLCJlbWFpbCI6Im5ndXllbmhvdGhlZGF0MjAyNUBnbWFpbC5jb20iLCJpYXQiOjE3NDY5NzY5MjAsImV4cCI6MTc0NzA2MzMyMH0.ADGIMnvcovAe4lyHCJOaxwunxF9cLUcGjQPyb8V3SeM

{
  "product_name": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch",
  "price": 4990000,
  "salePrice": 3690000,
  "stock": 100,
  "images": [
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_1_f163cb90590f4640bb0.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_1_42b4ca48ebbf461.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_2_f5e4262062d44022b0d.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_3_b1d37aab419940ed90a.webp"
  ],
  "rating": 4.9,
  "tags": [
  "Không dây",
  "ABS",
  "RGB"
],
  "bestSale": false,
  "flashSale": false,
    "contentBlock": [
    {
      "type": "text",
      "content": "<strong>Đánh giá chi tiết bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch</strong>"
    },
    {
      "type": "text",
      "content": "Dù bạn có am hiểu về công nghệ hay không thì bạn chắc chắn vẫn biết đến các thiết bị công nghệ của thương hiệu Asus như laptop Asus, màn hình Asus… Bên cạnh đó thì các thiết bị Gaming Gear đặc biệt là không thể nhắc đến Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch với nhiều công năng vượt trội, hãy cùng GEARVN tìm hiểu ngay sau đây."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/n_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___1__1024x1024.jpg",
      "alt": "image_1"
    },
    {
      "type": "text",
      "content": "<strong>Thiết kế thu gọn tối đa với bàn phím 96%</strong>"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless được xem là bàn phím 96% khi vẫn giữ lại toàn bộ các phím nhưng lại được thu gọn khoảng cách một cách tối đa, từ đó mà kích thước của chiếc bàn phím này chỉ lớn hơn bàn phím tiêu chuẩn 80% chỉ 1cm. Tuy là được thu gọn thiết kế một cách tối đa nhưng bàn phím lại mang trong mình vẻ cứng cáp và hoành tráng khi có cho mình trọng lượng"
    },
     {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___11__1024x1024.webp",
      "alt": "image_2"
    },
    {
      "type": "text",
      "content": "<strong>Màu sắc LED đồng bộ với nhiều thiết bị</strong>"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless sở hữu cho mình bộ LED RGB trong từng phím. Cùng với đó nếu bạn sở hữu laptop Asus, chuột Asus, tai nghe Asus các gamer sẽ còn được có thể sử dụng thêm tính năng Asus Aura sync đồng bộ ánh sáng và màu sắc cho mọi thiết bị Asus. Việc sở hữu khả năng thay đổi và kết hợp màu sắc cho sản phẩm công nghệ giúp cho trải nghiệm thư giãn cũng như chơi game của các gamer được nâng cấp lên một level mới."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___12__1024x1024.webp",
      "alt": "image_3"
    },
    {
      "type": "text",
      "content": "<strong>Sự kết hợp hoàn hảo cho dân gaming</strong>"
    },
    {
      "type": "text",
      "content": "Bạn sẽ có thể trải nghiệm cảm giác chơi game thuận tiện nhất khi bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch sở hữu cho mình tính năng Anti -Ghosting giúp anh em linh hoạt các nút bấm nhằm né được những đòn đánh và phản công địch một cách tối ưu. Bên cạnh đó, anh em có thể kích hoạt thêm Marco Key vào bất kỳ phím nào trên bàn phím để có thể linh hoạt và tiết kiệm thời gian nhất trong quá trình sử dụng."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/n_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___8__1024x1024.webp",
      "alt": "image_4"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch có thể là sự lựa chọn tối ưu của các anh em gamer không chỉ vì các tính năng kể trên mà chiếc bàn phím này còn hỗ trợ kết nối đa thiết bị thuận lợi cho việc sử dụng của anh em trên mọi mặt trận."
    }
  ],
  "category": "680518eb3556be73141264e8",
  "brand": "6805e67efea56b05826cc2d6",
  "vendor": "6805ebf6c350793d7da27a88"
}

### test create with not salePrince

POST http://localhost:8889/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODI0MDQwMjA5MzQwOGRhMzNjNzM4ZjMiLCJlbWFpbCI6InRoZWRhdEBnbWFpbC5jb20iLCJpYXQiOjE3NDg4MzI1MjUsImV4cCI6MTc0ODkxODkyNX0.tdeOc8lj8GyQbjIyi8hc6TXdzX5EwJLne5Pw_YXlXUI

{
  "product_name": "test with not salePrince",
  "price": 4990000,
  "stock": 100,
  "images": [
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_1_f163cb90590f4640bb0.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_1_42b4ca48ebbf461.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_2_f5e4262062d44022b0d.webp",
    "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/arvn_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch_3_b1d37aab419940ed90a.webp"
  ],
  "rating": 4.9,
  "tags": [
  "Không dây",
  "ABS",
  "RGB"
],
  "bestSale": false,
  "flashSale": false,
    "contentBlock": [
    {
      "type": "text",
      "content": "<strong>Đánh giá chi tiết bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch</strong>"
    },
    {
      "type": "text",
      "content": "Dù bạn có am hiểu về công nghệ hay không thì bạn chắc chắn vẫn biết đến các thiết bị công nghệ của thương hiệu Asus như laptop Asus, màn hình Asus… Bên cạnh đó thì các thiết bị Gaming Gear đặc biệt là không thể nhắc đến Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch với nhiều công năng vượt trội, hãy cùng GEARVN tìm hiểu ngay sau đây."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/n_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___1__1024x1024.jpg",
      "alt": "image_1"
    },
    {
      "type": "text",
      "content": "<strong>Thiết kế thu gọn tối đa với bàn phím 96%</strong>"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless được xem là bàn phím 96% khi vẫn giữ lại toàn bộ các phím nhưng lại được thu gọn khoảng cách một cách tối đa, từ đó mà kích thước của chiếc bàn phím này chỉ lớn hơn bàn phím tiêu chuẩn 80% chỉ 1cm. Tuy là được thu gọn thiết kế một cách tối đa nhưng bàn phím lại mang trong mình vẻ cứng cáp và hoành tráng khi có cho mình trọng lượng"
    },
     {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___11__1024x1024.webp",
      "alt": "image_2"
    },
    {
      "type": "text",
      "content": "<strong>Màu sắc LED đồng bộ với nhiều thiết bị</strong>"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless sở hữu cho mình bộ LED RGB trong từng phím. Cùng với đó nếu bạn sở hữu laptop Asus, chuột Asus, tai nghe Asus các gamer sẽ còn được có thể sử dụng thêm tính năng Asus Aura sync đồng bộ ánh sáng và màu sắc cho mọi thiết bị Asus. Việc sở hữu khả năng thay đổi và kết hợp màu sắc cho sản phẩm công nghệ giúp cho trải nghiệm thư giãn cũng như chơi game của các gamer được nâng cấp lên một level mới."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___12__1024x1024.webp",
      "alt": "image_3"
    },
    {
      "type": "text",
      "content": "<strong>Sự kết hợp hoàn hảo cho dân gaming</strong>"
    },
    {
      "type": "text",
      "content": "Bạn sẽ có thể trải nghiệm cảm giác chơi game thuận tiện nhất khi bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch sở hữu cho mình tính năng Anti -Ghosting giúp anh em linh hoạt các nút bấm nhằm né được những đòn đánh và phản công địch một cách tối ưu. Bên cạnh đó, anh em có thể kích hoạt thêm Marco Key vào bất kỳ phím nào trên bàn phím để có thể linh hoạt và tiết kiệm thời gian nhất trong quá trình sử dụng."
    },
    {
      "type": "image",
      "src": "http://localhost:8889/uploads/Ban_phim_Asus_ROG_Strix_Scope_II_96_Wireless_ROG_NX_Snow_Switch/n_ban_phim_asus_rog_strix_scope_ii_96_wireless_rog_nx_snow_switch___8__1024x1024.webp",
      "alt": "image_4"
    },
    {
      "type": "text",
      "content": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch có thể là sự lựa chọn tối ưu của các anh em gamer không chỉ vì các tính năng kể trên mà chiếc bàn phím này còn hỗ trợ kết nối đa thiết bị thuận lợi cho việc sử dụng của anh em trên mọi mặt trận."
    }
  ],
  "category": "680518eb3556be73141264e8",
  "brand": "6805e67efea56b05826cc2d6",
  "vendor": "6805ebf6c350793d7da27a88"
}


### update by id
PUT http://localhost:8889/api/v1/products/6820e53880a8734921371e03
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFjYWIzZmY2MTk4MjRmMWFhYzQzYzkiLCJlbWFpbCI6Im5ndXllbmhvdGhlZGF0MjAyNUBnbWFpbC5jb20iLCJpYXQiOjE3NDY5NzY5MjAsImV4cCI6MTc0NzA2MzMyMH0.ADGIMnvcovAe4lyHCJOaxwunxF9cLUcGjQPyb8V3SeM

{
    "product_name": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch",
    "description": "Bàn phím Asus ROG Strix Scope II 96 Wireless ROG NX Snow Switch là một lựa chọn cao cấp dành cho game thủ và người dùng chuyên nghiệp, kết hợp giữa thiết kế nhỏ gọn, hiệu suất cao và khả năng tùy biến linh hoạt."
}

### delete by id
DELETE http://localhost:8889/api/v1/products/67deea930d9bae179e3bc9df